global:
  scrape_interval: 5s

  evaluation_interval: 3s # waktu interval evaluasi dari setiap rule monitoring

scrape_configs:
  - job_name: exporter-prometheus-machine # Job
    static_configs:
      - targets:
      # list instance
        - localhost:9100
        # - 34.125.175.156:9100
        # - 34.125.35.211:9100
  - job_name: server-linux-via-dns
    dns_sd_configs: # dns service discovery
      - names:
          - prometheus-target.cobasaja.biz.id
        type: A
        port: 9100
  - job_name: prometheus-itself
    static_configs:
      - targets:
        - localhost:9090

# konfigurasi rule monitoring
rule_files:
  - 'rule-cpu-50-percent.yml' # berupa file

# jika sebuah rule terpenuhi maka akan mengirimakan alert ke Alertmanager
alerting:
  alertmanagers:
    - static_configs:
      - targets:
          - 'localhost:9093'